BASE_URL_DEV="https://nrlm.gov.in/"
BASE_URL_PROD="https://nrlm.gov.in/"
CLIENT_SECRET_KEY="dgtbncbehkcbjebccnkec78yf37bc"
REFRESH_TOKEN_URL="jhbheugcy2373y379y37gydygdy"
ENCRYPT_KEY = "$10A80$10A80$10A80$10A80$10A80$10A80$10A80$10A80";
ENCRYPT_IV_KEY = "$10A80$10A80$10A80$10A80$10A80$10A80$10A80$10A80";
CRYPLIBAES ="AES/CBC/PKCS5PADDING";
CRYPT_ID =  "8080808080808080"
CRYPT_IV = "8080808080808080"
WADH_KEY = "sgydIC09zzy6f8Lb3xaAqzKquKe9lFcNR9uTvYxFp+A="
SSL_PIN_1= "sha256/t2g2DXw0vWYjKaDq/d4dWk6MTb+Lho+sF01J4RIX3IU="
SSL_PIN_2= "sha256/rnhtVs65ADYfQGtMuB0jq2kZwwHy6/iqnBiUKcK1m0Y="


